//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResultatPartnerASAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseParticipant
    {
        public long CourseParticipantID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> CourseID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual User User { get; set; }
    }
}
